export { ReactComponent as IconAlert } from './Alert.svg';
export { ReactComponent as IconArrowRrimaryWhite } from './Arrow__primary-white.svg';
export { ReactComponent as IconBelastingen } from './belastingen.svg';
export { ReactComponent as IconMyNotifications } from './Bell.svg';
export { ReactComponent as IconBurgerZaken } from './burgerzaken.svg';
export { ReactComponent as IconCheckmark } from './Checkmark.svg';
export { ReactComponent as IconFilter } from './Filter.svg';
// export { ReactComponent as IconChevronDown } from './Chevron-Down.svg';
export { ReactComponent as IconChevronLeft } from './Chevron-Left.svg';
export { ReactComponent as IconChevronRight } from './Chevron-Right.svg';
// export { ReactComponent as IconChevronRight__primaryRed } from './Chevron-Right__primary-red.svg';
// export { ReactComponent as IconChevronRight__primaryWhite } from './Chevron-Right__primary-white.svg';
export { ReactComponent as IconClose } from './Close.svg';
// export { ReactComponent as IconClose__primaryWhite } from './Close__primary-white.svg';
export { ReactComponent as IconDocument } from './Document.svg';
export { ReactComponent as IconDownload } from './Download.svg';
export { ReactComponent as IconExternalLink } from './External-Link.svg';
export { ReactComponent as IconHomeSimple } from './home-simple.svg';
export { ReactComponent as IconHome } from './home.svg';
export { ReactComponent as IconHomeCommercial } from './home-commercial.svg';
export { ReactComponent as IconGarbage } from './Huisvuilkalender.svg';
export { ReactComponent as IconInfo } from './Info.svg';
export { ReactComponent as IconInkomen } from './inkomen.svg';
export { ReactComponent as IconLogout } from './Logout.svg';
// export { ReactComponent as IconMenu } from './Menu.svg';
export { ReactComponent as IconMijnGegevens } from './MijnGegevens.svg';
export { ReactComponent as IconMilieuzone } from './milieuzone.svg';
export { ReactComponent as IconProfile } from './Profile.svg';
export { ReactComponent as IconPassport } from './Passport.svg';
export { ReactComponent as IconSearch } from './Search.svg';
export { ReactComponent as IconTips } from './Tip.svg';
export { ReactComponent as IconWonen } from './wonen.svg';
export { ReactComponent as IconZorg } from './zorg.svg';
export { ReactComponent as IconVergunningen } from './vergunningen.svg';

// Map icons
export { ReactComponent as MapIconAfvalGlas } from './map/glas.svg';
export { ReactComponent as MapIconAfvalGft } from './map/gft.svg';
export { ReactComponent as MapIconAfvalPlastic } from './map/plastic.svg';
export { ReactComponent as MapIconAfvalTextiel } from './map/textile.svg';
export { ReactComponent as MapIconAfvalPapier } from './map/paper.svg';
export { ReactComponent as MapIconAfvalRest } from './map/trashcontainer.svg';
// export { ReactComponent as MapIconAuto } from './map/car.svg';
export { ReactComponent as MapIconBekendmaking } from './map/bekendmaking.svg';
export { ReactComponent as MapIconEvenement } from './map/evenement.svg';
export { ReactComponent as MapIconSport } from './map/sport.svg';
export { ReactComponent as MapIconHomeCommercial } from './map/homeCommercial__primary-red.svg';

export { ReactComponent as MapIconTennis } from './map/tennis.svg';
export { ReactComponent as MapIconVoetbal } from './map/voetbal.svg';
export { ReactComponent as MapIconFitness } from './map/fitness.svg';
export { ReactComponent as MapIconVolleybal } from './map/volleybal.svg';
export { ReactComponent as MapIconBasketbal } from './map/basketbal.svg';
