[
  {
    _links: {
      schema:
        'https://schemas.data.amsterdam.nl/datasets/duurzaamheid/energielabel/dataset#energielabel',
      self: [Object],
      bagVerblijfsobject: [Object],
      bagLigplaats: null,
      bagStandplaats: null,
      bagPand: [Object],
    },
    id: '20210304~1103LZ~813~~',
    opnamedatum: '2021-03-04',
    opnametype: 'Basisopname',
    status: 'Bestaand',
    berekeningstype: 'NTA 8800:2020 (basisopname woningbouw)',
    energieindex: null,
    energieklasse: 'G',
    energielabelIsPrive: null,
    isOpBasisVanReferentieGebouw: false,
    gebouwklasse: 'W',
    metingGeldigTot: '2031-03-04',
    registratiedatum: '2021-03-04',
    postcode: '1103LZ',
    huisnummer: 813,
    huisletter: null,
    huisnummertoevoeging: null,
    detailaanduiding: null,
    bagVerblijfsobjectId: '0363010000898840',
    bagLigplaatsId: null,
    bagStandplaatsId: null,
    bagPandId: '0363100012103711',
    gebouwtype: 'Appartement',
    gebouwsubtype: 'Hoekmidden',
    projectnaam: null,
    projectobject: null,
    sbicode: null,
    gebruiksoppervlakteThermischeZone: '55.90',
    energiebehoefte: '152.03',
    eisEnergiebehoefte: null,
    primaireFossieleEnergie: '456.35',
    eisPrimaireFossieleEnergie: null,
    primaireFossieleEnergieEmgForfaitair: null,
    aandeelHernieuwbareEnergie: '0.0',
    eisAandeelHernieuwbareEnergie: null,
    aandeelHernieuwbareEnergieEmgForfaitair: null,
    temperatuuroverschrijding: '1.56',
    eisTemperatuuroverschrijding: null,
    warmtebehoefte: '147.82',
    energieindexMetEmgForfaitair: null,
  },
];
