import { Chapter, Chapters } from '../../universal/config';
import { SVGComponent } from '../../universal/types';
import {
  IconAlert,
  IconAVG,
  IconBelastingen,
  IconBezwaren,
  IconBodem,
  IconBurgerZaken,
  IconErfpacht,
  IconErfpachtV2,
  IconGarbage,
  IconHomeCommercial,
  IconHoreca,
  IconInkomen,
  IconInkomenSVWI,
  IconKlachten,
  IconKrefia,
  IconMijnGegevens,
  IconMilieuzone,
  IconMyNotifications,
  IconOvertredingen,
  IconParkeren,
  IconSearch,
  IconSiaMeldingen,
  IconStadspas,
  IconSubsidie,
  IconToeristischeVerhuur,
  IconVergunningen,
  IconWior,
  IconZorg,
} from '../assets/icons';

export const ChapterIcons: Record<Chapter, SVGComponent> = {
  [Chapters.AFVAL]: IconGarbage,
  [Chapters.AVG]: IconAVG,
  [Chapters.BELASTINGEN]: IconBelastingen,
  [Chapters.BEZWAREN]: IconBezwaren,
  [Chapters.BURGERZAKEN]: IconBurgerZaken,
  [Chapters.BUURT]: IconWior,
  [Chapters.INKOMEN]: IconInkomen,
  [Chapters.INKOMEN_SVWI]: IconInkomenSVWI,
  [Chapters.STADSPAS]: IconStadspas,
  [Chapters.BRP]: IconMijnGegevens,
  [Chapters.MILIEUZONE]: IconMilieuzone,
  [Chapters.OVERTREDINGEN]: IconOvertredingen,
  [Chapters.SIA]: IconSiaMeldingen,
  [Chapters.NOTIFICATIONS]: IconMyNotifications,
  [Chapters.ROOT]: IconBurgerZaken,
  [Chapters.ERFPACHT]: IconErfpacht,
  [Chapters.ERFPACHTv2]: IconErfpachtV2,
  [Chapters.SUBSIDIE]: IconSubsidie,
  [Chapters.ZORG]: IconZorg,
  [Chapters.VERGUNNINGEN]: IconVergunningen,
  [Chapters.KVK]: IconHomeCommercial,
  [Chapters.TOERISTISCHE_VERHUUR]: IconToeristischeVerhuur,
  [Chapters.KREFIA]: IconKrefia,
  ALERT: IconAlert,
  [Chapters.SEARCH]: IconSearch,
  [Chapters.PARKEREN]: IconParkeren,
  [Chapters.KLACHTEN]: IconKlachten,
  [Chapters.HORECA]: IconHoreca,
  [Chapters.BODEM]: IconBodem,
};
