import { Thema } from '../../universal/config/thema';
import { SVGComponent } from '../../universal/types';
import {
  IconAFIS,
  IconAVG,
  IconBelastingen,
  IconBezwaren,
  IconBodem,
  IconBurgerZaken,
  IconErfpacht,
  IconGarbage,
  IconHLI,
  IconHomeCommercial,
  IconHoreca,
  IconInkomen,
  IconInkomenSVWI,
  IconKlachten,
  IconKrefia,
  IconMijnGegevens,
  IconMilieuzone,
  IconMyNotifications,
  IconOvertredingen,
  IconParkeren,
  IconSearch,
  IconSubsidie,
  IconToeristischeVerhuur,
  IconVaren,
  IconVergunningen,
  IconWior,
  IconZorg,
} from '../assets/icons';

export const ThemaIcons: Record<Thema, SVGComponent> = {
  AFIS: IconAFIS,
  VAREN: IconVaren,
  AFVAL: IconGarbage,
  AVG: IconAVG,
  BELASTINGEN: IconBelastingen,
  BEZWAREN: IconBezwaren,
  BODEM: IconBodem,
  BRP: IconMijnGegevens,
  BURGERZAKEN: IconBurgerZaken,
  BUURT: IconWior,
  ERFPACHT: IconErfpacht,
  ERFPACHTv2: IconErfpacht,
  HLI: IconHLI,
  HORECA: IconHoreca,
  INKOMEN: IconInkomen,
  KLACHTEN: IconKlachten,
  KREFIA: IconKrefia,
  KVK: IconHomeCommercial,
  MILIEUZONE: IconMilieuzone,
  NOTIFICATIONS: IconMyNotifications,
  OVERTREDINGEN: IconOvertredingen,
  PARKEREN: IconParkeren,
  HOME: IconBurgerZaken,
  SEARCH: IconSearch,
  SUBSIDIE: IconSubsidie,
  SVWI: IconInkomenSVWI,
  TOERISTISCHE_VERHUUR: IconToeristischeVerhuur,
  VERGUNNINGEN: IconVergunningen,
  ZORG: IconZorg,
};
