import { Thema, Themas } from '../../universal/config/thema';
import { SVGComponent } from '../../universal/types';
import {
  IconAFIS,
  IconAVG,
  IconAlert,
  IconBelastingen,
  IconBezwaren,
  IconBodem,
  IconBurgerZaken,
  IconErfpacht,
  IconGarbage,
  IconHLI,
  IconHomeCommercial,
  IconHoreca,
  IconInkomen,
  IconInkomenSVWI,
  IconJeugd,
  IconKlachten,
  IconKrefia,
  IconMijnGegevens,
  IconMilieuzone,
  IconMyNotifications,
  IconOvertredingen,
  IconParkeren,
  IconSearch,
  IconSubsidie,
  IconToeristischeVerhuur,
  IconVaren,
  IconVergunningen,
  IconWior,
  IconZorg,
} from '../assets/icons';

export const ThemaIcons: Record<Thema, SVGComponent> = {
  [Themas.AFIS]: IconAFIS,
  [Themas.VAREN]: IconVaren,
  [Themas.AFVAL]: IconGarbage,
  [Themas.AVG]: IconAVG,
  [Themas.BELASTINGEN]: IconBelastingen,
  [Themas.BEZWAREN]: IconBezwaren,
  [Themas.BODEM]: IconBodem,
  [Themas.BRP]: IconMijnGegevens,
  [Themas.BURGERZAKEN]: IconBurgerZaken,
  [Themas.BUURT]: IconWior,
  [Themas.ERFPACHT]: IconErfpacht,
  [Themas.ERFPACHTv2]: IconErfpacht,
  [Themas.HLI]: IconHLI,
  [Themas.HORECA]: IconHoreca,
  [Themas.INKOMEN]: IconInkomen,
  [Themas.KLACHTEN]: IconKlachten,
  [Themas.KREFIA]: IconKrefia,
  [Themas.KVK]: IconHomeCommercial,
  [Themas.MILIEUZONE]: IconMilieuzone,
  [Themas.NOTIFICATIONS]: IconMyNotifications,
  [Themas.OVERTREDINGEN]: IconOvertredingen,
  [Themas.PARKEREN]: IconParkeren,
  [Themas.ROOT]: IconBurgerZaken,
  [Themas.SEARCH]: IconSearch,
  [Themas.SUBSIDIE]: IconSubsidie,
  [Themas.SVWI]: IconInkomenSVWI,
  [Themas.JEUGD]: IconJeugd,
  [Themas.TOERISTISCHE_VERHUUR]: IconToeristischeVerhuur,
  [Themas.VERGUNNINGEN]: IconVergunningen,
  [Themas.ZORG]: IconZorg,
  ALERT: IconAlert,
};
