trigger:
  batch: true
  branches:
    include:
      - testen
      - az-acceptance
  paths:
    include:
      - src/client
      - src/universal
      - src/index.tsx
      - public
      - Dockerfile
      - package.json
      - package-lock.json

pr:
  autoCancel: true
  paths:
    include:
      - src/client
      - src/universal
      - src/index.tsx
      - public
      - Dockerfile
      - package.json
      - package-lock.json
  branches:
    include:
      - main

resources:
  repositories:
    - repository: MamsInfra
      type: git
      name: MijnAmsterdam/mijn-amsterdam-infra
      ref: refs/heads/pipeline-fe

parameters:
  - name: btdBuild
    type: boolean
    default: true
  - name: btdTest
    type: boolean
    default: true
  - name: btdDeploy
    type: boolean
    default: true
  - name: dtapName
    type: string
    default: none
    values:
      - none
      - t
      - a
      - p

  - name: updateAppSettings
    type: boolean
    default: false

variables:
  - ${{ if and(or(eq(variables['Build.SourceBranchName'], 'testen'), eq(variables['Build.Reason'], 'PullRequest')), eq(parameters.dtapName, 'none')) }}:
      - name: dtapName
        value: t
  - ${{ if and(eq(variables['Build.SourceBranchName'], 'az-acceptance'), eq(parameters.dtapName, 'none')) }}:
      - name: dtapName
        value: a
  - ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
      - name: btdDeploy
        value: false
  - ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
      - name: btdDeploy
        value: ${{ parameters.btdDeploy }}
      - name: dtapName
        value: ${{ parameters.dtapName }}

jobs:
  - template: pipelines/jobs/apps/btd-frontend.yaml@MamsInfra
    parameters:
      dtapName: ${{ variables.dtapName }}
      btdBuild: ${{ parameters.btdBuild }}
      btdTest: ${{ parameters.btdTest }}
      btdDeploy: ${{ variables.btdDeploy }}
      btdAppBFF: false
      btdAppUI: true
      updateAppSettings: ${{ parameters.updateAppSettings }}
      aquaScan: ${{ eq(variables['Build.Reason'], 'PullRequest') }}
