trigger:
  tags:
    include:
      - release-v*
pr: none

resources:
  repositories:
    - repository: MamsFrontend
      type: github
      endpoint: github.com_Amsterdam
      name: amsterdam/mijn-amsterdam-frontend
    - repository: MamsInfra
      type: git
      name: AMS-PRJ-MAMS/AMS-PRJ-MAMS
      ref: refs/heads/main

stages:
  - template: pipelines/btd-release-bff-ui.yaml@MamsInfra
