trigger:
  batch: true
  branches:
    include:
      - testen
      - az-acceptance
      - main
  paths:
    include:
      - azure-pipeline-ui.yaml
      - src/client
      - src/universal
      - src/index.tsx
      - public
      - Dockerfile
      - package.json
      - package-lock.json

pr:
  autoCancel: true
  paths:
    include:
      - src/client
      - src/universal
      - src/index.tsx
      - public
      - Dockerfile
      - package.json
      - package-lock.json
  branches:
    include:
      - main

resources:
  repositories:
    - repository: MamsInfra
      type: git
      name: MijnAmsterdam/mijn-amsterdam-infra
      ref: refs/heads/main

variables:
  - name: system.debug
    value: true
  - name: btdBuild
    value: true
  - name: btdDeploy
    value: true
  - name: btdTest
    value: true
  - name: dtapName
    value: t
  - ${{ if eq(variables['Build.SourceBranchName'], 'testen') }}:
      - name: btdTest
        value: false
  - ${{ if or(eq(variables['Build.SourceBranchName'], 'az-acceptance'), eq(variables['Build.SourceBranchName'], 'main')) }}:
      - name: dtapName
        value: a
  - ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
      - name: btdDeploy
        value: false

jobs:
  - template: pipelines/jobs/apps/btd-frontend.yaml@MamsInfra
    parameters:
      dtapName: ${{ variables.dtapName }}
      btdBuild: ${{ variables.btdBuild }}
      btdTest: ${{ variables.btdTest }}
      btdDeploy: ${{ variables.btdDeploy }}
      btdAppBFF: false
      btdAppUI: true
      aquaScan: ${{ eq(variables['Build.Reason'], 'PullRequest') }}
