trigger:
  tags:
    include:
      - release-v*
pr: none

resources:
  repositories:
    - repository: MamsInfra
      type: git
      name: MijnAmsterdam/mijn-amsterdam-infra
      ref: refs/heads/main

jobs:
  - ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main') }}:
      - template: pipelines/jobs/apps/btd-frontend.yaml@MamsInfra
        parameters:
          dtapName: p
          btdBuild: true
          btdTest: true
          btdDeploy: true
          btdAppBFF: true
          btdAppUI: true
  - ${{ if ne(variables['Build.SourceBranch'], 'refs/heads/main') }}:
      - job: EchoMessage
        displayName: 'Pipeline triggered on a releas tag on the wrong branch'
        steps:
          - script: echo "This pipeline is only triggered for the main branch"
            displayName: 'Print message'
