trigger:
  tags:
    include:
      - release-v*
pr: none

resources:
  repositories:
    - repository: MamsInfra
      type: git
      name: MijnAmsterdam/mijn-amsterdam-infra
      ref: refs/heads/main

jobs:
  - template: pipelines/btd-release-bff-ui.yaml@MamsInfra
