trigger:
  tags:
    include:
      - release-v*
pr: none

resources:
  repositories:
    - repository: MamsInfra
      type: git
      name: MijnAmsterdam/mijn-amsterdam-infra
      ref: refs/heads/main

jobs:
  - ${{ if contains(variables['Build.SourceBranchName'], 'refs/heads/main') }}:
      - template: pipelines/jobs/apps/btd-frontend.yaml@MamsInfra
        parameters:
          dtapName: p
          btdBuild: true
          btdTest: true
          btdDeploy: true
          btdAppBFF: true
          btdAppUI: true
  - job: EchoMessage
    displayName: 'Just prints a message for when the main branch condition is not met'
    steps:
      - script: echo "This pipeline is only triggered for the main branch"
        displayName: 'Print message'
