FROM node:10.15.3

# Indicating we are on a CI environment
ENV CI=true
# CRA will generate a file for the React runtime chunk, inlining it will cause issues with the CSP config
ENV INLINE_RUNTIME_CHUNK=false
ENV BUILD_ENV=test
ENV APP_PORT=80
ENV APP_HOST=mijn.ot.amsterdam.nl
ENV MOCK_API_PORT=5000
ENV MOCK_API_HOST=localhost

WORKDIR /app

# Copy required files for building
COPY package.json /app/
COPY package-lock.json /app/

RUN npm ci

COPY tsconfig.json /app/
COPY paths.json /app/
COPY .env.test /app/.env.production
COPY mock-api /app/mock-api
COPY src /app/src/
COPY scripts/proxy-serve.js /app/scripts/proxy-serve.js
COPY public /app/public/

# Setting the correct timezone for the build
RUN rm /etc/localtime
RUN ln -s /usr/share/zoneinfo/Europe/Amsterdam /etc/localtime

# Some conditional setup
RUN npm run build

CMD ["npm", "run", "serve-dev"]
