FROM node:13.7.0

# Indicating we are on a CI environment
ENV CI=true
# CRA will generate a file for the React runtime chunk, inlining it will cause issues with the CSP config
ENV INLINE_RUNTIME_CHUNK=false
ARG BUILD_ENV=test
ENV REACT_APP_BUILD_ENV=${BUILD_ENV}
ENV APP_PORT=80
ENV APP_HOST=mijn.ot.amsterdam.nl
ENV MOCK_API_PORT=5000
ENV MOCK_API_HOST=localhost

WORKDIR /app

# Copy required files for building
COPY package.json /app/
COPY package-lock.json /app/

RUN npm ci

COPY tsconfig.json /app/
COPY .env /app/.env
COPY mock-api /app/mock-api
COPY src /app/src/
COPY public /app/public/

# Setting the correct timezone for the build
RUN rm /etc/localtime
RUN ln -s /usr/share/zoneinfo/Europe/Amsterdam /etc/localtime

CMD ["npm", "run", "serve-dev"]
