FROM node:13.7.0

# Indicating we are on a CI environment
ENV CI=true
# CRA will generate a file for the React runtime chunk, inlining it will cause issues with the CSP config
ENV INLINE_RUNTIME_CHUNK=false

WORKDIR /app

# Copy required files for compilation
COPY package.json /app/
COPY package-lock.json /app/

RUN npm ci

COPY tsconfig.json /app/
COPY .env /app/.env
COPY mock-api /app/mock-api
COPY src /app/src/
COPY public /app/public/

# Setting the correct timezone for the build
RUN rm /etc/localtime
RUN ln -s /usr/share/zoneinfo/Europe/Amsterdam /etc/localtime

ENTRYPOINT [ "npm" ]
