allowBuilds:
  '@parcel/watcher': false
  core-js: false
  cpu-features: false
  es5-ext: false
  esbuild: false
  protobufjs: false
  ssh2: false
minimumReleaseAge: 1440 # 1440 minutes = 1 day
minimumReleaseAgeExclude:
  - concurrently@10.0.6 # This version fixes a critical issue by updating one of its dependencies
packages:
  - .
overrides:
  '@azure/app-configuration': '^1.12.1'
