allowBuilds:
  '@parcel/watcher': false
  core-js: false
  es5-ext: false
  esbuild: false
minimumReleaseAge: 1440 # 1440 minutes = 1 day
minimumReleaseAgeExclude:
  - '@amsterdam/piwik-tracker-react@3.0.0-alpha.2' # We are testing this version to release the major version of this package
  - '@amsterdam/piwik-tracker@3.0.0-alpha.2' # We are testing this version to release the major version of this package
packages:
  - .
