allowBuilds:
  '@parcel/watcher': false
  core-js: false
  cpu-features: false
  es5-ext: false
  esbuild: false
  protobufjs: false
  ssh2: false
minimumReleaseAge: 1440 # 1440 minutes = 1 day
minimumReleaseAgeExclude:
  - '@amsterdam/piwik-tracker-react@3.0.0' # We deployed this package ourselves and want to be the first that test it
  - '@amsterdam/piwik-tracker@3.0.0' # We deployed this package ourselves and want to be the first that test it
packages:
  - .
overrides:
  '@azure/app-configuration': '^1.12.1'
