---
openapi: 3.1.0
components:
  schemas:
    ContactType:
      type: string
      enum:
      - Email
      - Telefoonnummer
      - Adres
      - AppId
    ContactgegevenRequest:
      description: Request object voor het toevoegen van een contactgegeven aan een
        partij
      type: object
      required:
      - type
      - waarde
      properties:
        type:
          $ref: "#/components/schemas/ContactType"
        waarde:
          type: string
        scope:
          $ref: "#/components/schemas/ScopeRequest"
    ContactgegevenResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        type:
          $ref: "#/components/schemas/ContactType"
        waarde:
          type: string
        isGeverifieerd:
          type: boolean
        isValid:
          type: boolean
        createdAt:
          $ref: "#/components/schemas/LocalDateTime"
        lastUpdated:
          $ref: "#/components/schemas/LocalDateTime"
        scopes:
          type: array
          items:
            $ref: "#/components/schemas/ScopeResponse"
    ContactgegevenUpdateRequest:
      type: object
      required:
      - type
      - waarde
      properties:
        type:
          $ref: "#/components/schemas/ContactType"
        waarde:
          type: string
        scope:
          $ref: "#/components/schemas/ScopeRequest"
        id:
          type: integer
          format: int64
    DienstRequest:
      description: Request object voor het toevoegen van een dienst aan een dienstverlener
      type: object
      required:
      - beschrijving
      properties:
        beschrijving:
          type: string
          pattern: \S
    DienstResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        beschrijving:
          type: string
    DienstverlenerRequest:
      description: Request object voor het toevoegen van een dienstverlener
      type: object
      required:
      - naam
      - oin
      properties:
        naam:
          type: string
        oin:
          type: string
    EmailVerificatieRequest:
      description: Request object voor het verifiëren van een emailadres
      type: object
      required:
      - email
      - identificatieNummer
      - identificatieType
      - verificatieCode
      properties:
        email:
          type: string
        identificatieNummer:
          type: string
        identificatieType:
          $ref: "#/components/schemas/IdentificatieType"
        verificatieCode:
          type: string
    IdentificatieResponse:
      type: object
      properties:
        identificatieType:
          $ref: "#/components/schemas/IdentificatieType"
        identificatieNummer:
          type: string
    IdentificatieType:
      type: string
      enum:
      - BSN
      - KVK
      - RSIN
    LocalDateTime:
      type: string
      format: date-time
      examples:
      - 2022-03-10T12:15:50
    PartijRequest:
      description: Request object voor extra informatie meesturen bij van een Partij
      type: object
      properties:
        dienstverlener:
          type: string
        dienstverlenerOin:
          type: string
        dienstBeschrijving:
          type: string
    PartijResponse:
      type: object
      properties:
        partijId:
          type: integer
          format: int64
        identificaties:
          type: array
          items:
            $ref: "#/components/schemas/IdentificatieResponse"
        voorkeuren:
          type: array
          items:
            $ref: "#/components/schemas/VoorkeurResponse"
        contactgegevens:
          type: array
          items:
            $ref: "#/components/schemas/ContactgegevenResponse"
    ScopeRequest:
      type: object
      properties:
        scopeIdentificatieType:
          $ref: "#/components/schemas/IdentificatieType"
        scopeIdentificatieNummer:
          type: string
        dienstId:
          type: integer
          format: int64
    ScopeResponse:
      type: object
      properties:
        partij:
          $ref: "#/components/schemas/IdentificatieResponse"
        dienst:
          $ref: "#/components/schemas/DienstResponse"
    VoorkeurRequest:
      type: object
      required:
      - voorkeurType
      - waarde
      properties:
        voorkeurType:
          $ref: "#/components/schemas/VoorkeurType"
        waarde:
          type: string
        scope:
          $ref: "#/components/schemas/ScopeRequest"
    VoorkeurResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        voorkeurType:
          $ref: "#/components/schemas/VoorkeurType"
        waarde:
          type: string
        createdAt:
          $ref: "#/components/schemas/LocalDateTime"
        lastUpdated:
          $ref: "#/components/schemas/LocalDateTime"
        scopes:
          type: array
          items:
            $ref: "#/components/schemas/ScopeResponse"
    VoorkeurType:
      type: string
      enum:
      - WebsiteTaal
      - MagGebeldWorden
      - WebsiteThema
      - Aanhef
      - OntvangViaBerichtenbox
    VoorkeurUpdateRequest:
      type: object
      required:
      - voorkeurType
      - waarde
      properties:
        voorkeurType:
          $ref: "#/components/schemas/VoorkeurType"
        waarde:
          type: string
        scope:
          $ref: "#/components/schemas/ScopeRequest"
        id:
          type: integer
          format: int64
tags:
- name: Dienstverlener
  description: Endpoints voor het beheren van dienstverleners en diensten
- name: EmailVerificatie
  description: Endpoints voor het verifiëren van emails
- name: Profiel
  description: Endpoints voor het beheren van partijen
paths:
  /api/profielservice/v1/contactgegeven/{identificatieType}/{identificatieNummer}:
    put:
      summary: Update contactgegeven van een partij
      description: "Werk type, waarde en scope van een contactgegeven bij. Identificatie\
        \ kan niet aangepast worden."
      tags:
      - Profiel
      parameters:
      - name: identificatieNummer
        in: path
        required: true
        schema:
          type: string
      - name: identificatieType
        in: path
        required: true
        schema:
          $ref: "#/components/schemas/IdentificatieType"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ContactgegevenUpdateRequest"
        required: true
      responses:
        "200":
          description: Contactgegeven succesvol bijgewerkt
          content:
            application/json:
              schema: {}
        "404":
          description: Contactgegeven of partij niet gevonden
        "400":
          description: Bad Request
    post:
      summary: Toevoegen nieuwe contactgegeven voor een partij
      description: Voegt een nieuwe contactgegeven toe. Creëert automatisch ontbrekende
        partijen.
      tags:
      - Profiel
      parameters:
      - name: identificatieNummer
        in: path
        required: true
        schema:
          type: string
      - name: identificatieType
        in: path
        required: true
        schema:
          $ref: "#/components/schemas/IdentificatieType"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ContactgegevenRequest"
        required: true
      responses:
        "201":
          description: Contactgegeven succesvol toegevoegd
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ContactgegevenResponse"
        "200":
          description: Contactgegeven was al geregistreerd voor deze partij en scope
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ContactgegevenResponse"
        "400":
          description: Bad Request
  /api/profielservice/v1/contactgegeven/{identificatieType}/{identificatieNummer}/{contactgegevenId}:
    delete:
      summary: Verwijder contactgegeven van een partij
      description: Verwijdert een contactgegeven volledig
      tags:
      - Profiel
      parameters:
      - name: contactgegevenId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: identificatieNummer
        in: path
        required: true
        schema:
          type: string
      - name: identificatieType
        in: path
        required: true
        schema:
          $ref: "#/components/schemas/IdentificatieType"
      responses:
        "204":
          description: Contactgegeven succesvol verwijderd
        "404":
          description: Contactgegeven of partij niet gevonden
  /api/profielservice/v1/dienstverlener:
    post:
      tags:
      - Dienstverlener
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DienstverlenerRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema: {}
        "400":
          description: Bad Request
      summary: Add Dienstverlener
  /api/profielservice/v1/dienstverlener/{DienstverlenerNaam}/diensten:
    post:
      summary: Voegt een dienst toe aan een dienstverlener
      description: Voegt een nieuwe dienst toe met beschrijving
      tags:
      - Dienstverlener
      parameters:
      - name: DienstverlenerNaam
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DienstRequest"
        required: true
      responses:
        "201":
          description: Dienst succesvol toegevoegd
        "404":
          description: Dienstverlener niet gevonden
        "400":
          description: Bad Request
  /api/profielservice/v1/dienstverlener/{naam}:
    get:
      tags:
      - Dienstverlener
      parameters:
      - name: naam
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema: {}
      summary: Get Diensten Dienstverlener
  /api/profielservice/v1/emailverificatie:
    post:
      tags:
      - EmailVerificatie
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/EmailVerificatieRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema: {}
        "400":
          description: Bad Request
      summary: Post Email Verificatie
  /api/profielservice/v1/voorkeur/{identificatieType}/{identificatieNummer}:
    put:
      summary: Update voorkeur van een partij
      description: "Werk type, waarde en scope van een voorkeur bij. Identificatie\
        \ kan niet aangepast worden."
      tags:
      - Profiel
      parameters:
      - name: identificatieNummer
        in: path
        required: true
        schema:
          type: string
      - name: identificatieType
        in: path
        required: true
        schema:
          $ref: "#/components/schemas/IdentificatieType"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/VoorkeurUpdateRequest"
        required: true
      responses:
        "200":
          description: Voorkeur succesvol bijgewerkt
          content:
            application/json:
              schema: {}
        "404":
          description: Voorkeur of partij niet gevonden
        "400":
          description: Bad Request
    post:
      summary: Toevoegen nieuwe voorkeur voor een partij
      description: Voegt een nieuwe voorkeur toe. Creëert automatisch ontbrekende
        partijen.
      tags:
      - Profiel
      parameters:
      - name: identificatieNummer
        in: path
        required: true
        schema:
          type: string
      - name: identificatieType
        in: path
        required: true
        schema:
          $ref: "#/components/schemas/IdentificatieType"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/VoorkeurRequest"
        required: true
      responses:
        "201":
          description: Voorkeur succesvol toegevoegd
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/VoorkeurResponse"
        "200":
          description: Voorkeur was al geregistreerd voor deze partij en scope
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/VoorkeurResponse"
        "400":
          description: Bad Request
  /api/profielservice/v1/voorkeur/{identificatieType}/{identificatieNummer}/{voorkeurId}:
    delete:
      summary: Verwijder voorkeur van een partij
      description: Verwijdert een voorkeur volledig
      tags:
      - Profiel
      parameters:
      - name: identificatieNummer
        in: path
        required: true
        schema:
          type: string
      - name: identificatieType
        in: path
        required: true
        schema:
          $ref: "#/components/schemas/IdentificatieType"
      - name: voorkeurId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "204":
          description: Voorkeur succesvol verwijderd
        "404":
          description: Voorkeur of partij niet gevonden
  /api/profielservice/v1/{identificatieType}/{identificatieNummer}:
    get:
      summary: Ophalen profiel van een partij
      description: Haalt het profiel op van een partij
      tags:
      - Profiel
      parameters:
      - name: identificatieNummer
        in: path
        required: true
        schema:
          type: string
      - name: identificatieType
        in: path
        required: true
        schema:
          $ref: "#/components/schemas/IdentificatieType"
      - name: dienstBeschrijving
        in: query
        schema:
          type: string
      - name: dienstverlener
        in: query
        schema:
          type: string
      - name: oin
        in: query
        schema:
          type: string
      responses:
        "200":
          description: Partij succesvol opgehaald
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PartijResponse"
        "404":
          description: Partij niet gevonden of is verwijderd
info:
  title: profiel-service API
  version: 1.0.0-SNAPSHOT
