export enum CaseType {
  TVMRVVObject = 'TVM - RVV - Object',
  GPK = 'GPK',
  GPP = 'GPP',
  EvenementMelding = 'Evenement melding',
  EvenementVergunning = 'Evenement vergunning',
  Omzettingsvergunning = 'Omzettingsvergunning',
  ERVV = 'E-RVV - TVM',
  VakantieVerhuur = 'Vakantieverhuur',
  VakantieverhuurVergunningaanvraag = 'Vakantieverhuur vergunningsaanvraag',
  BBVergunning = 'B&B - vergunning',
  BZP = 'Parkeerontheffingen Blauwe zone particulieren',
  BZB = 'Parkeerontheffingen Blauwe zone bedrijven',
  Flyeren = 'Flyeren-Sampling',
  AanbiedenDiensten = 'Aanbieden van diensten',
  NachtwerkOntheffing = 'Nachtwerkontheffing',
  ZwaarVerkeer = 'Zwaar verkeer',
  Samenvoegingsvergunning = 'Samenvoegingsvergunning',
  Onttrekkingsvergunning = 'Onttrekkingsvergunning voor ander gebruik',
  OnttrekkingsvergunningSloop = 'Onttrekkingsvergunning voor sloop',
  VormenVanWoonruimte = 'Woningvormingsvergunning',
  Splitsingsvergunning = 'Splitsingsvergunning',
  VOB = 'VOB',
}
