#! /bin/bash

# Stop execution on error
set -e

current_branch=$(git status | head -1 | awk {'print $3'})
has_mijn=$(echo "$current_branch" | grep --only-matching 'MIJN')

if [ ! -n "$has_mijn" ]; then
  echo "No MIJN in branch found. proceed? [Y-n]"
  read proceed
  if [ proceed != "Y" && proceed != "y" ]; then
    echo "Exitting..."
    exit 0
  fi
fi

echo "MIJN found, safe!"
echo "Deploying to test"

git checkout testen
git reset --hard "$current_branch"
git push --force
git checkout -
