import { IS_AP, IS_DEVELOPMENT, IS_OT, IS_PRODUCTION } from './env';

export const FeatureToggle = {
  afisActive: !IS_AP,
  avgActive: true,
  bbDocumentDownloadsActive: IS_OT,
  bekendmakingenDatasetActive: false,
  belastingApiActive: true,
  bezwarenActive: true,
  bodemActive: true,
  cleopatraApiActive: true,
  cmsFooterActive: true,
  dbDisabled: false,
  decosServiceActive: IS_OT,
  ehKetenmachtigingActive: !IS_PRODUCTION,
  eherkenningActive: true,
  erfpachtV2Active: !IS_PRODUCTION,
  erfpachtV2EndpointActive: !IS_PRODUCTION,
  evenementenDatasetActive: false,
  garbageInformationPage: true,
  hliThemaActive: !IS_PRODUCTION,
  horecaActive: true,
  identiteitsbewijzenActive: true,
  inkomenBBZActive: true,
  isSearchEnabled: true,
  klachtenActive: true,
  krefiaActive: true,
  kvkActive: true,
  laadpalenActive: !IS_PRODUCTION,
  meldingenBuurtActive: true,
  oidcLogoutHintActive: true,
  overtredingenActive: !IS_PRODUCTION,
  parkerenActive: true,
  passQueryParamsToStreamUrl: !IS_AP,
  powerbrowserActive: !IS_PRODUCTION,
  profileToggleActive: true,
  residentCountActive: true,
  sportDatasetsActive: true,
  stadspasRequestsActive: false,
  subsidieActive: true,
  svwiLinkActive: IS_DEVELOPMENT,
  tipsFlipActive: true,
  toeristischeVerhuurActive: true,
  vergunningenActive: true,
  vergunningenV2Active: IS_OT,
  wiorDatasetActive: true,
  wiorMeldingen: true,
  zorgnedDocumentAttachmentsActive: true,
};

// For testing and development purposes we can pass a set of arbitrary parameters to the BFF.
// For example, tipsCompareDate=2023-01-31 this will change the date that is used to compare with dates being used in the tips controller.
export const streamEndpointQueryParamKeys = {
  tipsCompareDate: 'tipsCompareDate',
};

export const DEFAULT_PROFILE_TYPE = 'private';

// NOTE: Keep up-to-date with _colors.scss
export const Colors = {
  white: 'white',
  black: 'black',
  primaryRed: '#EC0000',
  primaryDarkblue: '#004699',
  neutralGrey1: '#F5F5F5',
  neutralGrey2: '#E6E6E6',
  neutralGrey3: '#B4B4B4',
  neutralGrey4: '#767676',
  neutralGrey5: '#323232',
  supportValid: '#00A03C',
  supportInvalid: '#EC0000',
  supportFocus: '#FEC813',
  supportPurple: '#A00078',
  supportPink: '#E50082',
  supportOrange: '#FF9100',
  supportYellow: '#FFE600',
  supportLightgreen: '#BED200',
  supportDarkgreen: '#00A03C',
  supportLightblue: '#009DEC',
  overlayBlack50: 'rgba(0, 0, 0, 0.5)',
};
