import { IS_AP, IS_DEVELOPMENT, IS_OT, IS_PRODUCTION, IS_TAP } from './env';

export const FeatureToggle = {
  afisActive: !IS_PRODUCTION,
  afisEmandatesActive: false,
  avgActive: true,
  bbDocumentDownloadsActive: IS_OT,
  bekendmakingenDatasetActive: false,
  belastingApiActive: true,
  bezwarenActive: true,
  bodemActive: true,
  cleopatraApiActive: true,
  cmsFooterActive: true,
  dbEnabled: IS_TAP,
  dbSessionsEnabled: IS_TAP,
  decosServiceActive: IS_DEVELOPMENT, // TODO: Enable when working on MIJN-8914
  ehKetenmachtigingActive: !IS_PRODUCTION,
  eherkenningActive: true,
  erfpachtV2Active: !IS_PRODUCTION,
  erfpachtV2EndpointActive: !IS_PRODUCTION,
  evenementenDatasetActive: false,
  garbageInformationPage: true,
  hliThemaActive: !IS_PRODUCTION,
  horecaActive: true,
  identiteitsbewijzenActive: true,
  inkomenBBZActive: true,
  isSearchEnabled: true,
  klachtenActive: true,
  krefiaActive: true,
  kvkActive: true,
  laadpalenActive: !IS_PRODUCTION,
  meldingenBuurtActive: true,
  oidcLogoutHintActive: true,
  overtredingenActive: !IS_PRODUCTION,
  parkerenActive: IS_PRODUCTION, // Two parkeren toggles because in the middle of implementing MIJN-9097.
  parkerenPatroonC: !IS_PRODUCTION,
  passQueryParamsToStreamUrl: !IS_AP,
  powerbrowserActive: !IS_PRODUCTION,
  profileToggleActive: true,
  residentCountActive: true,
  sportDatasetsActive: true,
  subsidieActive: true,
  svwiLinkActive: IS_DEVELOPMENT,
  tipsFlipActive: true,
  toeristischeVerhuurActive: true,
  vergunningenActive: true,
  vergunningenV2Active: IS_DEVELOPMENT, // TODO: Enable when working on MIJN-8914
  wiorDatasetActive: true,
  wiorMeldingen: true,
  zorgnedDocumentAttachmentsActive: true,
  zorgnedDocumentDecisionDateActive: !IS_PRODUCTION,
  zorgv2ThemapaginaActive: !IS_PRODUCTION,
};
