import { MOCK_BASE_PATH } from '../settings.ts';
import type { MockRouteDefinition } from '../types.ts';

export const routes: MockRouteDefinition[] = [
  {
    id: 'get-test-accounts-digid',
    url: `${MOCK_BASE_PATH}/test-accounts/digid`,
    method: 'GET',
    handler: {
      type: 'json',
      status: 200,
      body: {
        tableHeaders: [
          {
            displayName: 'Gebruikersnaam',
            key: 'username',
          },
          {
            displayName: 'BSN',
            key: 'profileId',
          },
          {
            key: 'brpBsn',
            displayName: 'BrpBsn',
          },
          {
            key: 'mokum',
            displayName: 'Mokum',
          },
          {
            key: 'hasChildren',
            displayName: 'HasChildren',
          },
          {
            key: 'partnerName',
            displayName: 'PartnerName',
          },
          {
            key: 'isOlderThan18',
            displayName: 'IsOlderThan18',
          },
          {
            key: 'hasParents',
            displayName: 'HasParents',
          },
          {
            key: 'hasVertrokkenOnbekendWaarheen',
            displayName: 'HasVertrokkenOnbekendWaarheen',
          },
          {
            key: 'isAdresInOnderzoek',
            displayName: 'IsAdresInOnderzoek',
          },
          {
            key: 'heeftStadspas',
            displayName: 'HeeftStadspas',
          },
          {
            key: 'availableThemas',
            displayName: 'AvailableThemas',
          },
        ],
        accounts: [
          {
            brpBsn: '999998651',
            mokum: false,
            hasChildren: false,
            partnerName: '',
            isOlderThan18: false,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas: 'Mijn gegevens, Contact met de gemeente',
            username: 'Aanduiding-naam-gebruik(E)',
            profileId: '999998651',
          },
          {
            brpBsn: '999994669',
            mokum: false,
            hasChildren: true,
            partnerName: 'Jacoba Magdalena',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas: 'Mijn gegevens, Contact met de gemeente',
            username: 'Aanduiding-naam-gebruik(N)',
            profileId: '999994669',
          },
          {
            brpBsn: '999996538',
            mokum: false,
            hasChildren: true,
            partnerName: 'Olivia Ghislaine',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas: 'Mijn gegevens, Contact met de gemeente',
            username: 'Aanduiding-naam-gebruik(P)',
            profileId: '999996538',
          },
          {
            brpBsn: '999971189',
            mokum: false,
            hasChildren: true,
            partnerName: 'Hans Otto',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas: 'Mijn gegevens, Contact met de gemeente',
            username: 'Aanduiding-naam-gebruik(V)',
            profileId: '999971189',
          },
          {
            brpBsn: '999993987',
            mokum: false,
            hasChildren: false,
            partnerName: '',
            isOlderThan18: true,
            hasParents: false,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas: 'Mijn gegevens, Contact met de gemeente',
            username: 'AanduidingHuisnummer1',
            profileId: '999993987',
          },
          {
            brpBsn: '999992624',
            mokum: false,
            hasChildren: false,
            partnerName: 'Hassan',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas: 'Mijn gegevens, Contact met de gemeente',
            username: 'AanduidingHuisnummer2',
            profileId: '999992624',
          },
          {
            brpBsn: '999971086',
            mokum: true,
            hasChildren: true,
            partnerName: '',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Afval, Mijn gegevens, Parkeren, Contact met de gemeente',
            username: 'Abayomi',
            profileId: '999971086',
          },
          {
            brpBsn: '999971098',
            mokum: true,
            hasChildren: false,
            partnerName: '',
            isOlderThan18: false,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Afval, Mijn gegevens, Parkeren, Contact met de gemeente',
            username: 'Abayomi-Akwasi',
            profileId: '999971098',
          },
          {
            brpBsn: '999991838',
            mokum: false,
            hasChildren: true,
            partnerName: '',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas: 'Mijn gegevens, Contact met de gemeente',
            username: 'AdresCase1',
            profileId: '999991838',
          },
          {
            brpBsn: '999990159',
            mokum: false,
            hasChildren: false,
            partnerName: 'Tessa',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas: 'Mijn gegevens, Contact met de gemeente',
            username: 'AdresCase2',
            profileId: '999990159',
          },
          {
            brpBsn: '999990081',
            mokum: false,
            hasChildren: false,
            partnerName: 'Cees',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas: 'Mijn gegevens, Contact met de gemeente',
            username: 'AdresCase3',
            profileId: '999990081',
          },
          {
            brpBsn: '999970008',
            mokum: false,
            hasChildren: true,
            partnerName: 'Grada',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: true,
            heeftStadspas: false,
            availableThemas: 'Mijn gegevens, Contact met de gemeente',
            username: 'AdresInOnderzoek1',
            profileId: '999970008',
          },
          {
            brpBsn: '999970288',
            mokum: false,
            hasChildren: false,
            partnerName: '',
            isOlderThan18: false,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas: 'Mijn gegevens, Contact met de gemeente',
            username: 'AdresInOnderzoek2',
            profileId: '999970288',
          },
          {
            brpBsn: '999970331',
            mokum: false,
            hasChildren: false,
            partnerName: '',
            isOlderThan18: false,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas: 'Mijn gegevens, Contact met de gemeente',
            username: 'AdresInOnderzoek3',
            profileId: '999970331',
          },
          {
            brpBsn: '999971074',
            mokum: true,
            hasChildren: true,
            partnerName: '',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Afval, Mijn gegevens, Parkeren, Contact met de gemeente',
            username: 'Akwasi',
            profileId: '999971074',
          },
          {
            brpBsn: '999995832',
            mokum: true,
            hasChildren: false,
            partnerName: '',
            isOlderThan18: false,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Afval, Mijn gegevens, Parkeren, Contact met de gemeente',
            username: 'Alexander-den-Braber',
            profileId: '999995832',
          },
          {
            brpBsn: '999997464',
            mokum: true,
            hasChildren: false,
            partnerName: '',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Afval, Mijn gegevens, Parkeren, Contact met de gemeente',
            username: 'Alida-Almenkinders',
            profileId: '999997464',
          },
          {
            brpBsn: '999992958',
            mokum: true,
            hasChildren: true,
            partnerName: 'Jonathan',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Afval, Mijn gegevens, Parkeren, Contact met de gemeente',
            username: 'Anita-van-Buren',
            profileId: '999992958',
          },
          {
            brpBsn: '999994402',
            mokum: true,
            hasChildren: false,
            partnerName: '',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Afval, Mijn gegevens, Parkeren, Contact met de gemeente',
            username: 'Anna-Hðrhildur-Salvarsdðttir',
            profileId: '999994402',
          },
          {
            brpBsn: '999994797',
            mokum: true,
            hasChildren: true,
            partnerName: '',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Afval, Mijn gegevens, Parkeren, Contact met de gemeente',
            username: 'Anne-Jan-Boer',
            profileId: '999994797',
          },
          {
            brpBsn: '999993641',
            mokum: true,
            hasChildren: true,
            partnerName: '',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Afval, Mijn gegevens, Parkeren, Contact met de gemeente',
            username: 'Antonius-Johannes-Joseph-Wellingasterveen',
            profileId: '999993641',
          },
          {
            brpBsn: '999994724',
            mokum: true,
            hasChildren: true,
            partnerName: 'Patricia',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: true,
            availableThemas:
              'Afval, Bezwaren, Bodem, Mijn gegevens, Stadspas en regelingen bij laag inkomen, Horeca, Klachten, Parkeren, Contact met de gemeente, Toeristische verhuur, Vergunningen en ontheffingen, Zorg en ondersteuning, Inkomen',
            username: 'Ayda-Kumari',
            profileId: '999991619',
          },
          {
            brpBsn: '999994724',
            mokum: true,
            hasChildren: true,
            partnerName: 'Patricia',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: true,
            availableThemas:
              'Afval, Bezwaren, Bodem, Mijn gegevens, Stadspas en regelingen bij laag inkomen, Horeca, Klachten, Parkeren, Contact met de gemeente, Toeristische verhuur, Vergunningen en ontheffingen, Zorg en ondersteuning, Inkomen',
            username: 'Ayda02',
            profileId: '999991619',
          },
          {
            heeftStadspas: false,
            availableThemas:
              'Belastingen, Bodem, Stadspas en regelingen bij laag inkomen, Contact met de gemeente, Subsidies, Toeristische verhuur, Vergunningen en ontheffingen, Zorg en ondersteuning',
            username: 'Ayda03',
            profileId: '123459916',
          },
          {
            brpBsn: '999991747',
            mokum: true,
            hasChildren: false,
            partnerName: 'Bernard',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Afval, Mijn gegevens, Parkeren, Contact met de gemeente',
            username: 'Ayse-Bilgiç',
            profileId: '999991747',
          },
          {
            brpBsn: '999992399',
            mokum: true,
            hasChildren: false,
            partnerName: '',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Afval, AVG persoonsgegevens, Bezwaren, Bodem, Mijn gegevens, Parkeren, Contact met de gemeente, Toeristische verhuur, Vergunningen en ontheffingen, Zorg en ondersteuning, Inkomen',
            username: 'Bahareh02',
            profileId: '999992399',
          },
          {
            brpBsn: '999997725',
            mokum: true,
            hasChildren: true,
            partnerName: '',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Afval, Mijn gegevens, Parkeren, Contact met de gemeente',
            username: 'Beatrijs-Verbeek',
            profileId: '999997725',
          },
          {
            brpBsn: '999994062',
            mokum: true,
            hasChildren: false,
            partnerName: '',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Afval, Mijn gegevens, Parkeren, Contact met de gemeente',
            username: 'Behnam-Kumari',
            profileId: '999994062',
          },
          {
            brpBsn: '999993215',
            mokum: true,
            hasChildren: true,
            partnerName: 'Ayse',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Afval, Mijn gegevens, Parkeren, Contact met de gemeente',
            username: 'Bernard-Schoon',
            profileId: '999993215',
          },
          {
            brpBsn: '999991309',
            mokum: true,
            hasChildren: false,
            partnerName: 'Gezina',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Afval, Mijn gegevens, Parkeren, Contact met de gemeente',
            username: 'Bertje-Fruitplukker',
            profileId: '999991309',
          },
          {
            brpBsn: '999998304',
            mokum: true,
            hasChildren: false,
            partnerName: '',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Afval, Mijn gegevens, Parkeren, Contact met de gemeente',
            username: 'Bram-Schoon',
            profileId: '999998304',
          },
          {
            brpBsn: '999991280',
            mokum: false,
            hasChildren: true,
            partnerName: '',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas: 'Mijn gegevens, Contact met de gemeente',
            username: 'BriefadresBuitenAmsterdam1',
            profileId: '999991280',
          },
          {
            brpBsn: '999994293',
            mokum: false,
            hasChildren: true,
            partnerName: 'Karin Monique',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas: 'Mijn gegevens, Contact met de gemeente',
            username: 'BriefadresBuitenAmsterdam1a',
            profileId: '999994293',
          },
          {
            brpBsn: '999991929',
            mokum: false,
            hasChildren: true,
            partnerName: 'Robert',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas: 'Mijn gegevens, Contact met de gemeente',
            username: 'BriefadresBuitenAmsterdam1b',
            profileId: '999991929',
          },
          {
            brpBsn: '999997701',
            mokum: false,
            hasChildren: true,
            partnerName: '',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas: 'Mijn gegevens, Contact met de gemeente',
            username: 'BriefadresBuitenAmsterdam1c',
            profileId: '999997701',
          },
          {
            brpBsn: '999994815',
            mokum: true,
            hasChildren: true,
            partnerName: '',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Afval, Mijn gegevens, Parkeren, Contact met de gemeente',
            username: 'Bruno-Schoonzinger',
            profileId: '999994815',
          },
          {
            brpBsn: '999997944',
            mokum: true,
            hasChildren: false,
            partnerName: 'Miranda',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Afval, Mijn gegevens, Parkeren, Contact met de gemeente',
            username: 'Christina-Koetsier',
            profileId: '999997944',
          },
          {
            brpBsn: '999993550',
            mokum: false,
            hasChildren: false,
            partnerName: '',
            isOlderThan18: false,
            hasParents: false,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas: 'Mijn gegevens, Contact met de gemeente',
            username: 'Christine-Jansen-de-Groot',
            profileId: '999993550',
          },
          {
            brpBsn: '999996903',
            mokum: true,
            hasChildren: false,
            partnerName: '',
            isOlderThan18: true,
            hasParents: false,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Afval, Mijn gegevens, Parkeren, Contact met de gemeente',
            username: 'Dariusz-Kuchar',
            profileId: '999996903',
          },
          {
            brpBsn: '999996800',
            mokum: true,
            hasChildren: false,
            partnerName: '',
            isOlderThan18: false,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Afval, Mijn gegevens, Parkeren, Contact met de gemeente',
            username: 'David-Almenkinders',
            profileId: '999996800',
          },
          {
            brpBsn: '999993203',
            mokum: true,
            hasChildren: true,
            partnerName: 'Jan',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Afval, Mijn gegevens, Parkeren, Contact met de gemeente',
            username: 'Dorothea-Snijder',
            profileId: '999993203',
          },
          {
            brpBsn: '999998894',
            mokum: false,
            hasChildren: false,
            partnerName: '',
            isOlderThan18: false,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas: 'Mijn gegevens, Contact met de gemeente',
            username: 'DubbeleNationaliteit1',
            profileId: '999998894',
          },
          {
            brpBsn: '999970355',
            mokum: false,
            hasChildren: false,
            partnerName: '',
            isOlderThan18: false,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas: 'Mijn gegevens, Contact met de gemeente',
            username: 'DubbeleNationaliteit2',
            profileId: '999970355',
          },
          {
            brpBsn: '999970367',
            mokum: false,
            hasChildren: false,
            partnerName: '',
            isOlderThan18: false,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas: 'Mijn gegevens, Contact met de gemeente',
            username: 'DubbeleNationaliteit3',
            profileId: '999970367',
          },
          {
            brpBsn: '999970379',
            mokum: false,
            hasChildren: false,
            partnerName: '',
            isOlderThan18: false,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas: 'Mijn gegevens, Contact met de gemeente',
            username: 'DubbeleNationaliteit4',
            profileId: '999970379',
          },
          {
            brpBsn: '999970380',
            mokum: false,
            hasChildren: false,
            partnerName: '',
            isOlderThan18: false,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas: 'Mijn gegevens, Contact met de gemeente',
            username: 'DubbeleNationaliteit5',
            profileId: '999970380',
          },
          {
            brpBsn: '999993367',
            mokum: true,
            hasChildren: false,
            partnerName: '',
            isOlderThan18: true,
            hasParents: false,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Afval, Mijn gegevens, Parkeren, Contact met de gemeente',
            username: 'El-Nawal-Hussein-Mohamed',
            profileId: '999993367',
          },
          {
            brpBsn: '999996794',
            mokum: true,
            hasChildren: false,
            partnerName: '',
            isOlderThan18: false,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Afval, Mijn gegevens, Parkeren, Contact met de gemeente',
            username: 'Elias-Almenkinders',
            profileId: '999996794',
          },
          {
            brpBsn: '999996824',
            mokum: true,
            hasChildren: false,
            partnerName: '',
            isOlderThan18: false,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Afval, Mijn gegevens, Parkeren, Contact met de gemeente',
            username: 'Esther-Almenkinders',
            profileId: '999996824',
          },
          {
            brpBsn: '999993008',
            mokum: true,
            hasChildren: false,
            partnerName: 'Youssef Saïd',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Afval, Mijn gegevens, Parkeren, Contact met de gemeente, Zorg en ondersteuning',
            username: 'Fatima-Saïda-Al-Ksar-el-Kebir',
            profileId: '999993008',
          },
          {
            brpBsn: '999991802',
            mokum: true,
            hasChildren: false,
            partnerName: '',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Afval, Mijn gegevens, Parkeren, Contact met de gemeente, Zorg en ondersteuning',
            username: "Frans-in-'t-Veld",
            profileId: '999991802',
          },
          {
            brpBsn: '999992958',
            mokum: true,
            hasChildren: true,
            partnerName: 'Jonathan',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Afval, Bodem, Mijn gegevens, Stadspas en regelingen bij laag inkomen, Parkeren, Contact met de gemeente, Zorg en ondersteuning',
            username: 'Gerard22',
            profileId: '123459862',
          },
          {
            brpBsn: '999991875',
            mokum: true,
            hasChildren: false,
            partnerName: '',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Afval, Mijn gegevens, Parkeren, Contact met de gemeente',
            username: 'Gerardus-Johannes-Wilhelmus-Blokzijl',
            profileId: '999991875',
          },
          {
            brpBsn: '999991139',
            mokum: true,
            hasChildren: false,
            partnerName: '',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Afval, Mijn gegevens, Parkeren, Contact met de gemeente',
            username:
              'Gerardus-Rudolfus-Adrianus-Petrus-Josephus-Eduardus-de-Vries-alias-Prins-de-Lignac+-Ridder-van-het-Land-van-Ooit+-Baron-van-Bobbejaansland+-Graaf-van-het-Verdronken-land-van-Saeftinghe+-Markies-van-het-Verdronken-land-van-Reimerswaal',
            profileId: '999991139',
          },
          {
            brpBsn: '999995030',
            mokum: true,
            hasChildren: false,
            partnerName: 'Pieter',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Afval, Belastingen, Mijn gegevens, Stadspas en regelingen bij laag inkomen, Parkeren, Contact met de gemeente',
            username: 'gerardusrudolfus',
            profileId: '307741928',
          },
          {
            brpBsn: '999994542',
            mokum: true,
            hasChildren: true,
            partnerName: 'Wilma',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Facturen en betalen, Afval, Bezwaren, Bodem, Mijn gegevens, Horeca, Kredietbank & FIBU, Parkeren, Contact met de gemeente, Toeristische verhuur, Vergunningen en ontheffingen',
            username: 'Gerrit-den-Braber',
            profileId: '999994542',
          },
          {
            brpBsn: '999993008',
            mokum: true,
            hasChildren: false,
            partnerName: 'Youssef Saïd',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Afval, Belastingen, Mijn gegevens, Milieuzone, Parkeren, Contact met de gemeente, Toeristische verhuur, Vergunningen en ontheffingen, Zorg en ondersteuning, Inkomen',
            username: 'gerrit03',
            profileId: '307741837',
          },
          {
            brpBsn: '999994542',
            mokum: true,
            hasChildren: true,
            partnerName: 'Wilma',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Facturen en betalen, Afval, Bezwaren, Bodem, Mijn gegevens, Horeca, Kredietbank & FIBU, Parkeren, Contact met de gemeente, Toeristische verhuur, Vergunningen en ontheffingen',
            username: 'Gerrit04',
            profileId: '999994542',
          },
          {
            brpBsn: '999993720',
            mokum: true,
            hasChildren: false,
            partnerName: 'Bertje',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Afval, Mijn gegevens, Parkeren, Contact met de gemeente',
            username: 'Gezina-Boomsma',
            profileId: '999993720',
          },
          {
            brpBsn: '999996873',
            mokum: true,
            hasChildren: false,
            partnerName: '',
            isOlderThan18: true,
            hasParents: false,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Afval, Mijn gegevens, Parkeren, Contact met de gemeente',
            username: 'Grzegorz-Janik',
            profileId: '999996873',
          },
          {
            brpBsn: '999996964',
            mokum: true,
            hasChildren: false,
            partnerName: '',
            isOlderThan18: true,
            hasParents: false,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Afval, Mijn gegevens, Parkeren, Contact met de gemeente',
            username: 'Grzegorz-Wojciechowski',
            profileId: '999996964',
          },
          {
            brpBsn: '999991553',
            mokum: true,
            hasChildren: true,
            partnerName: 'Karel Maria',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Afval, Mijn gegevens, Parkeren, Contact met de gemeente',
            username: 'Guðrún-Sigríður-Sigurðardóttir',
            profileId: '999991553',
          },
          {
            brpBsn: '999996745',
            mokum: true,
            hasChildren: false,
            partnerName: '',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Afval, Mijn gegevens, Parkeren, Contact met de gemeente',
            username: 'Hendrika-Almenkinders',
            profileId: '999996745',
          },
          {
            brpBsn: '999990810',
            mokum: true,
            hasChildren: false,
            partnerName: 'Helène',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Afval, Bezwaren, Bodem, Mijn gegevens, Kredietbank & FIBU, Parkeren, Contact met de gemeente, Toeristische verhuur, Vergunningen en ontheffingen',
            username: 'Hendrika-Isabella-Gerarda-Johanna-de-Roos',
            profileId: '999990810',
          },
          {
            brpBsn: '999990536',
            mokum: true,
            hasChildren: true,
            partnerName: 'Hendrikus Theodorus',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Afval, Mijn gegevens, Stadspas en regelingen bij laag inkomen, Parkeren, Contact met de gemeente',
            username: 'Hendrika-Johanna-Theodora-Grupstal',
            profileId: '999990536',
          },
          {
            brpBsn: '999990810',
            mokum: true,
            hasChildren: false,
            partnerName: 'Helène',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Afval, Bezwaren, Bodem, Mijn gegevens, Kredietbank & FIBU, Parkeren, Contact met de gemeente, Toeristische verhuur, Vergunningen en ontheffingen',
            username: 'Hendrika02',
            profileId: '999990810',
          },
          {
            brpBsn: '999991747',
            mokum: true,
            hasChildren: false,
            partnerName: 'Bernard',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: true,
            availableThemas:
              'Afval, Mijn gegevens, Stadspas en regelingen bij laag inkomen, Parkeren, Contact met de gemeente',
            username: 'Hendrika03',
            profileId: '912345664',
          },
          {
            brpBsn: '999992661',
            mokum: false,
            hasChildren: false,
            partnerName: 'Anne-Marie',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Bezwaren, Bodem, Mijn gegevens, Stadspas en regelingen bij laag inkomen, Contact met de gemeente, Subsidies, Toeristische verhuur, Inkomen',
            username: 'Hendrika04',
            profileId: '123460013',
          },
          {
            brpBsn: '999991474',
            mokum: true,
            hasChildren: true,
            partnerName: 'Hendrika Johanna Theodora',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Afval, Mijn gegevens, Parkeren, Contact met de gemeente',
            username: 'Hendrikus-Theodorus-Streeveld',
            profileId: '999991474',
          },
          {
            brpBsn: '999996770',
            mokum: true,
            hasChildren: false,
            partnerName: '',
            isOlderThan18: false,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Afval, Mijn gegevens, Parkeren, Contact met de gemeente',
            username: 'Hillegonda-Almenkinders',
            profileId: '999996770',
          },
          {
            brpBsn: '999996885',
            mokum: true,
            hasChildren: false,
            partnerName: '',
            isOlderThan18: true,
            hasParents: false,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Afval, Mijn gegevens, Parkeren, Contact met de gemeente',
            username: 'Igor-Haczek',
            profileId: '999996885',
          },
          {
            brpBsn: '999994323',
            mokum: true,
            hasChildren: false,
            partnerName: '',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Afval, Mijn gegevens, Parkeren, Contact met de gemeente',
            username: 'Imako-Tamaran',
            profileId: '999994323',
          },
          {
            brpBsn: '999992624',
            mokum: false,
            hasChildren: false,
            partnerName: 'Hassan',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Belastingen, Mijn gegevens, Stadspas en regelingen bij laag inkomen, Contact met de gemeente',
            username: 'Imako02',
            profileId: '123459953',
          },
          {
            brpBsn: '999997932',
            mokum: true,
            hasChildren: false,
            partnerName: 'Miranda',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Afval, Mijn gegevens, Parkeren, Contact met de gemeente',
            username: 'Izaak-Bloem',
            profileId: '999997932',
          },
          {
            brpBsn: '000009908',
            mokum: true,
            hasChildren: true,
            partnerName: '',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Afval, Mijn gegevens, Parkeren, Contact met de gemeente',
            username: 'Iñes-María-Núria-de-Velázquez',
            profileId: '000009908',
          },
          {
            brpBsn: '999998298',
            mokum: true,
            hasChildren: false,
            partnerName: '',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Afval, Mijn gegevens, Parkeren, Contact met de gemeente',
            username: 'Jan-Adriaan-Almenkinders',
            profileId: '999998298',
          },
          {
            brpBsn: '999992995',
            mokum: true,
            hasChildren: true,
            partnerName: '',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Afval, Mijn gegevens, Parkeren, Contact met de gemeente',
            username: 'Jan-Goedmut',
            profileId: '999992995',
          },
          {
            brpBsn: '999993604',
            mokum: true,
            hasChildren: false,
            partnerName: '',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Afval, Mijn gegevens, Parkeren, Contact met de gemeente',
            username: 'Jan-Moes',
            profileId: '999993604',
          },
          {
            brpBsn: '000009994',
            mokum: true,
            hasChildren: false,
            partnerName: '',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Afval, Mijn gegevens, Parkeren, Contact met de gemeente',
            username: 'Jantje-Testing',
            profileId: '000009994',
          },
          {
            brpBsn: '999996927',
            mokum: true,
            hasChildren: false,
            partnerName: '',
            isOlderThan18: true,
            hasParents: false,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Afval, Mijn gegevens, Parkeren, Contact met de gemeente',
            username: 'Janusz-Kszczot',
            profileId: '999996927',
          },
          {
            brpBsn: '999997002',
            mokum: true,
            hasChildren: false,
            partnerName: 'Nathalia',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas: 'Mijn gegevens, Parkeren, Contact met de gemeente',
            username: 'Jasper-Roeland-van-Duijn',
            profileId: '999997002',
          },
          {
            brpBsn: '999992715',
            mokum: true,
            hasChildren: false,
            partnerName: '',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Afval, Mijn gegevens, Parkeren, Contact met de gemeente, Zorg en ondersteuning',
            username: 'Jochem-Verstraten',
            profileId: '999992715',
          },
          {
            brpBsn: '999992132',
            mokum: true,
            hasChildren: false,
            partnerName: '',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Afval, Mijn gegevens, Parkeren, Contact met de gemeente',
            username: 'Johannes-Hendrikus-Jacobus-Käster',
            profileId: '999992132',
          },
          {
            brpBsn: '999996307',
            mokum: true,
            hasChildren: false,
            partnerName: 'Anita',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Afval, Mijn gegevens, Parkeren, Contact met de gemeente',
            username: 'Jonathan-Postma',
            profileId: '999996307',
          },
          {
            brpBsn: '999991565',
            mokum: true,
            hasChildren: false,
            partnerName: '',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Afval, Mijn gegevens, Parkeren, Contact met de gemeente',
            username: 'Joost-Jan-Haarlem',
            profileId: '999991565',
          },
          {
            brpBsn: '999994724',
            mokum: true,
            hasChildren: true,
            partnerName: 'Patricia',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Afval, Mijn gegevens, Parkeren, Contact met de gemeente, Zorg en ondersteuning',
            username: 'Joost-Verstraten',
            profileId: '999994724',
          },
          {
            brpBsn: '999990524',
            mokum: false,
            hasChildren: false,
            partnerName: 'Jim Kim',
            isOlderThan18: true,
            hasParents: false,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: true,
            availableThemas:
              'Belastingen, Bezwaren, Bodem, Mijn gegevens, Stadspas en regelingen bij laag inkomen, Klachten, Contact met de gemeente, Subsidies, Vergunningen en ontheffingen, Zorg en ondersteuning, Inkomen, Onderwijs en Jeugd',
            username: 'Joost02',
            profileId: '123457348',
          },
          {
            brpBsn: '999996897',
            mokum: true,
            hasChildren: false,
            partnerName: '',
            isOlderThan18: true,
            hasParents: false,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Afval, Mijn gegevens, Parkeren, Contact met de gemeente',
            username: 'Kacper-Korzeniowski',
            profileId: '999996897',
          },
          {
            brpBsn: '010755561',
            mokum: true,
            hasChildren: false,
            partnerName: '',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Afval, Mijn gegevens, Parkeren, Contact met de gemeente',
            username: 'Karel-Koolmees',
            profileId: '010755561',
          },
          {
            brpBsn: '999998286',
            mokum: true,
            hasChildren: false,
            partnerName: '',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Afval, Mijn gegevens, Parkeren, Contact met de gemeente',
            username: 'Karen-Kristel-Kathleen-Schoonzinger',
            profileId: '999998286',
          },
          {
            brpBsn: '010245741',
            mokum: true,
            hasChildren: false,
            partnerName: '',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Afval, Mijn gegevens, Parkeren, Contact met de gemeente',
            username: 'Karin-Koolmees',
            profileId: '010245741',
          },
          {
            brpBsn: '999970355',
            mokum: false,
            hasChildren: false,
            partnerName: '',
            isOlderThan18: false,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Belastingen, Bodem, Mijn gegevens, Contact met de gemeente',
            username: 'LennertLapzwans',
            profileId: '690013449',
          },
          {
            brpBsn: '999991000',
            mokum: true,
            hasChildren: false,
            partnerName: '',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Afval, Bodem, Mijn gegevens, Parkeren, Contact met de gemeente, Vergunningen en ontheffingen',
            username: 'Liselotte12',
            profileId: '999991000',
          },
          {
            brpBsn: '999996782',
            mokum: true,
            hasChildren: false,
            partnerName: '',
            isOlderThan18: false,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Afval, Mijn gegevens, Parkeren, Contact met de gemeente',
            username: 'Magdalena-Almenkinders',
            profileId: '999996782',
          },
          {
            brpBsn: '999996952',
            mokum: true,
            hasChildren: false,
            partnerName: '',
            isOlderThan18: true,
            hasParents: false,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Afval, Mijn gegevens, Parkeren, Contact met de gemeente',
            username: 'Marek-Pyrek',
            profileId: '999996952',
          },
          {
            brpBsn: '999992892',
            mokum: true,
            hasChildren: false,
            partnerName: '',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Afval, Mijn gegevens, Parkeren, Contact met de gemeente',
            username: 'Mari-Anne-Verstraten',
            profileId: '999992892',
          },
          {
            brpBsn: '999997920',
            mokum: true,
            hasChildren: false,
            partnerName: 'Christina',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Afval, Mijn gegevens, Parkeren, Contact met de gemeente',
            username: 'Miranda-Schoppenhouwer',
            profileId: '999997920',
          },
          {
            brpBsn: '999996812',
            mokum: true,
            hasChildren: false,
            partnerName: '',
            isOlderThan18: false,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Afval, Mijn gegevens, Parkeren, Contact met de gemeente',
            username: 'Miriam-Almenkinders',
            profileId: '999996812',
          },
          {
            brpBsn: '999996769',
            mokum: true,
            hasChildren: true,
            partnerName: '',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas: 'Mijn gegevens, Parkeren, Contact met de gemeente',
            username: 'Monique-Dijkhuizen',
            profileId: '999996769',
          },
          {
            brpBsn: '999991103',
            mokum: true,
            hasChildren: false,
            partnerName: 'Johanna',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas: 'Mijn gegevens, Parkeren, Contact met de gemeente',
            username: 'Ouder1Adellijketitel',
            profileId: '999991103',
          },
          {
            brpBsn: '999994888',
            mokum: false,
            hasChildren: false,
            partnerName: '',
            isOlderThan18: true,
            hasParents: false,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: true,
            heeftStadspas: false,
            availableThemas:
              'Bodem, Mijn gegevens, Contact met de gemeente, Subsidies',
            username: 'Paula01',
            profileId: '303937828',
          },
          {
            brpBsn: '999996861',
            mokum: true,
            hasChildren: false,
            partnerName: '',
            isOlderThan18: true,
            hasParents: false,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Afval, Mijn gegevens, Parkeren, Contact met de gemeente',
            username: 'Pawel-Demczyszak',
            profileId: '999996861',
          },
          {
            brpBsn: '999993586',
            mokum: false,
            hasChildren: false,
            partnerName: '',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: true,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas: 'Mijn gegevens, Contact met de gemeente',
            username: 'petrivornowski',
            profileId: '302641828',
          },
          {
            brpBsn: '999993926',
            mokum: true,
            hasChildren: true,
            partnerName: 'Jacoba Magdalena',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Facturen en betalen, Mijn gegevens, Parkeren, Contact met de gemeente',
            username: 'Petrus-Paulus-Leemstra',
            profileId: '999993926',
          },
          {
            brpBsn: '999993173',
            mokum: true,
            hasChildren: true,
            partnerName: '',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Afval, Mijn gegevens, Parkeren, Contact met de gemeente',
            username: 'Piet-Streeveld',
            profileId: '999993173',
          },
          {
            brpBsn: '999994141',
            mokum: true,
            hasChildren: true,
            partnerName: 'Ria',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Afval, Mijn gegevens, Parkeren, Contact met de gemeente',
            username: 'Piet-Verstraten',
            profileId: '999994141',
          },
          {
            brpBsn: '999997476',
            mokum: true,
            hasChildren: false,
            partnerName: '',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Afval, Mijn gegevens, Parkeren, Contact met de gemeente',
            username: 'Pieter-Almenkinders',
            profileId: '999997476',
          },
          {
            brpBsn: '010082426',
            mokum: true,
            hasChildren: false,
            partnerName: 'Rianne',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Afval, Mijn gegevens, Parkeren, Contact met de gemeente',
            username: 'Pieter-Verstratenmaker',
            profileId: '010082426',
          },
          {
            brpBsn: '999992727',
            mokum: true,
            hasChildren: false,
            partnerName: '',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Afval, Mijn gegevens, Parkeren, Contact met de gemeente',
            username: 'Pietje-Streeveld',
            profileId: '999992727',
          },
          {
            brpBsn: '999993343',
            mokum: true,
            hasChildren: false,
            partnerName: '',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Afval, Mijn gegevens, Parkeren, Contact met de gemeente',
            username: 'Pjotter-Parsjenko',
            profileId: '999993343',
          },
          {
            brpBsn: '999992855',
            mokum: false,
            hasChildren: false,
            partnerName: '',
            isOlderThan18: true,
            hasParents: false,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas: 'Mijn gegevens, Contact met de gemeente',
            username: 'Provincie-Adellijketitel1',
            profileId: '999992855',
          },
          {
            heeftStadspas: false,
            availableThemas: 'Contact met de gemeente',
            username: 'Provincie-Adellijketitel10',
            profileId: '99999403',
          },
          {
            heeftStadspas: false,
            availableThemas: 'Contact met de gemeente',
            username: 'Provincie-Adellijketitel11',
            profileId: '99999466',
          },
          {
            heeftStadspas: false,
            availableThemas: 'Contact met de gemeente',
            username: 'Provincie-Adellijketitel12',
            profileId: '99999482',
          },
          {
            heeftStadspas: false,
            availableThemas: 'Contact met de gemeente',
            username: 'Provincie-Adellijketitel13',
            profileId: '99999348',
          },
          {
            heeftStadspas: false,
            availableThemas: 'Contact met de gemeente',
            username: 'Provincie-Adellijketitel14',
            profileId: '99999030',
          },
          {
            brpBsn: '999994888',
            mokum: false,
            hasChildren: false,
            partnerName: '',
            isOlderThan18: true,
            hasParents: false,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: true,
            heeftStadspas: false,
            availableThemas: 'Mijn gegevens, Contact met de gemeente',
            username: 'Provincie-Adellijketitel2',
            profileId: '999994888',
          },
          {
            brpBsn: '999993951',
            mokum: false,
            hasChildren: true,
            partnerName: 'Jean Louis Firmin',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas: 'Mijn gegevens, Contact met de gemeente',
            username: 'Provincie-Adellijketitel3',
            profileId: '999993951',
          },
          {
            brpBsn: '999992016',
            mokum: false,
            hasChildren: false,
            partnerName: '',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas: 'Mijn gegevens, Contact met de gemeente',
            username: 'Provincie-Adellijketitel4',
            profileId: '999992016',
          },
          {
            brpBsn: '999971256',
            mokum: false,
            hasChildren: false,
            partnerName: '',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas: 'Mijn gegevens, Contact met de gemeente',
            username: 'Provincie-Adellijketitel5',
            profileId: '999971256',
          },
          {
            brpBsn: '999992788',
            mokum: false,
            hasChildren: false,
            partnerName: '',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas: 'Mijn gegevens, Contact met de gemeente',
            username: 'Provincie-Adellijketitel6',
            profileId: '999992788',
          },
          {
            brpBsn: '999990160',
            mokum: false,
            hasChildren: false,
            partnerName: '',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas: 'Mijn gegevens, Contact met de gemeente',
            username: 'Provincie-Adellijketitel7',
            profileId: '999990160',
          },
          {
            brpBsn: '999992922',
            mokum: false,
            hasChildren: false,
            partnerName: '',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas: 'Mijn gegevens, Contact met de gemeente',
            username: 'Provincie-Adellijketitel8',
            profileId: '999992922',
          },
          {
            brpBsn: '999995029',
            mokum: false,
            hasChildren: false,
            partnerName: '',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas: 'Mijn gegevens, Contact met de gemeente',
            username: 'Provincie-Adellijketitel9',
            profileId: '999995029',
          },
          {
            brpBsn: '999990512',
            mokum: false,
            hasChildren: true,
            partnerName: '',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: true,
            availableThemas:
              'AVG persoonsgegevens, Bezwaren, Bodem, Mijn gegevens, Stadspas en regelingen bij laag inkomen, Horeca, Klachten, Contact met de gemeente, Toeristische verhuur, Vergunningen en ontheffingen',
            username: 'Provincie-Barbara02',
            profileId: '999990512',
          },
          {
            brpBsn: '999992661',
            mokum: false,
            hasChildren: false,
            partnerName: 'Anne-Marie',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas: 'Mijn gegevens, Contact met de gemeente',
            username: 'Provincie-Huisletter1',
            profileId: '999992661',
          },
          {
            brpBsn: '999994979',
            mokum: false,
            hasChildren: false,
            partnerName: '',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas: 'Mijn gegevens, Contact met de gemeente',
            username: 'Provincie-Huisletter2',
            profileId: '999994979',
          },
          {
            brpBsn: '999990524',
            mokum: false,
            hasChildren: false,
            partnerName: 'Jim Kim',
            isOlderThan18: true,
            hasParents: false,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas: 'Mijn gegevens, Contact met de gemeente',
            username: 'Provincie-Huisnummertoevoeging1',
            profileId: '999990524',
          },
          {
            brpBsn: '999991449',
            mokum: false,
            hasChildren: false,
            partnerName: 'Kim',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas: 'Mijn gegevens, Parkeren, Contact met de gemeente',
            username: 'Provincie-Huisnummertoevoeging2',
            profileId: '999991449',
          },
          {
            brpBsn: '999995182',
            mokum: false,
            hasChildren: true,
            partnerName: 'Henk',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: true,
            availableThemas:
              'Mijn gegevens, Stadspas en regelingen bij laag inkomen, Parkeren, Contact met de gemeente',
            username: 'Provincie-Jansma001',
            profileId: '999995182',
          },
          {
            brpBsn: '999994104',
            mokum: false,
            hasChildren: true,
            partnerName: '',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Bodem, Mijn gegevens, Kredietbank & FIBU, Contact met de gemeente, Toeristische verhuur',
            username: 'Provincie-Marga02',
            profileId: '999994104',
          },
          {
            brpBsn: '999994311',
            mokum: false,
            hasChildren: false,
            partnerName: '',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: true,
            availableThemas:
              'Bezwaren, Mijn gegevens, Stadspas en regelingen bij laag inkomen, Contact met de gemeente, Subsidies',
            username: 'Provincie-Pierre12',
            profileId: '999994311',
          },
          {
            brpBsn: '999991826',
            mokum: true,
            hasChildren: false,
            partnerName: '',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Afval, Bezwaren, Bodem, Mijn gegevens, Parkeren, Contact met de gemeente, Toeristische verhuur',
            username: 'ReneeWolters01',
            profileId: '999991826',
          },
          {
            brpBsn: '000009908',
            mokum: true,
            hasChildren: true,
            partnerName: '',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Afval, Mijn gegevens, Milieuzone, Parkeren, Contact met de gemeente, Subsidies, Vergunningen en ontheffingen',
            username: 'Rente01',
            profileId: '000000012',
          },
          {
            brpBsn: '999991826',
            mokum: true,
            hasChildren: false,
            partnerName: '',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Afval, Bezwaren, Bodem, Mijn gegevens, Parkeren, Contact met de gemeente, Toeristische verhuur',
            username: 'Renée-Wolters',
            profileId: '999991826',
          },
          {
            brpBsn: '999990901',
            mokum: true,
            hasChildren: true,
            partnerName: 'Piet',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Afval, Mijn gegevens, Parkeren, Contact met de gemeente',
            username: 'Ria-van-Amstel',
            profileId: '999990901',
          },
          {
            brpBsn: '999995030',
            mokum: true,
            hasChildren: false,
            partnerName: 'Pieter',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Afval, Mijn gegevens, Parkeren, Contact met de gemeente, Zorg en ondersteuning',
            username: 'Rianne-van-Amstel',
            profileId: '999995030',
          },
          {
            brpBsn: '999996848',
            mokum: true,
            hasChildren: false,
            partnerName: '',
            isOlderThan18: true,
            hasParents: false,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Afval, Mijn gegevens, Parkeren, Contact met de gemeente',
            username: 'Robert-Lewandoski',
            profileId: '999996848',
          },
          {
            brpBsn: '999993793',
            mokum: true,
            hasChildren: false,
            partnerName: '',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas: 'Mijn gegevens, Parkeren, Contact met de gemeente',
            username: 'Rodney-Plieger',
            profileId: '999993793',
          },
          {
            brpBsn: '999992211',
            mokum: true,
            hasChildren: false,
            partnerName: '',
            isOlderThan18: true,
            hasParents: false,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas: 'Mijn gegevens, Parkeren, Contact met de gemeente',
            username: 'Ron-van-Wees',
            profileId: '999992211',
          },
          {
            brpBsn: '999990779',
            mokum: true,
            hasChildren: false,
            partnerName: '',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Belastingen, Bezwaren, Bodem, Mijn gegevens, Horeca, Kredietbank & FIBU, Milieuzone, Parkeren, Contact met de gemeente, Toeristische verhuur, Vergunningen en ontheffingen, Zorg en ondersteuning',
            username: 'Ronald-Franciscus-Maria-Moes',
            profileId: '999990779',
          },
          {
            brpBsn: '999990779',
            mokum: true,
            hasChildren: false,
            partnerName: '',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Belastingen, Bezwaren, Bodem, Mijn gegevens, Horeca, Kredietbank & FIBU, Milieuzone, Parkeren, Contact met de gemeente, Toeristische verhuur, Vergunningen en ontheffingen, Zorg en ondersteuning',
            username: 'ronald01',
            profileId: '999990779',
          },
          {
            brpBsn: '999991863',
            mokum: true,
            hasChildren: false,
            partnerName: 'Willemijn',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Afval, Mijn gegevens, Parkeren, Contact met de gemeente',
            username: 'Rowan-Helpmore',
            profileId: '999991863',
          },
          {
            brpBsn: '999997713',
            mokum: true,
            hasChildren: false,
            partnerName: '',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Afval, Mijn gegevens, Parkeren, Contact met de gemeente',
            username: 'Shireen-Verbeek',
            profileId: '999997713',
          },
          {
            brpBsn: '999996939',
            mokum: true,
            hasChildren: false,
            partnerName: '',
            isOlderThan18: true,
            hasParents: false,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Afval, Mijn gegevens, Parkeren, Contact met de gemeente',
            username: 'Tomasz-Magdziarczyk',
            profileId: '999996939',
          },
          {
            brpBsn: '999990202',
            mokum: true,
            hasChildren: false,
            partnerName: 'Ellen',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Belastingen, Mijn gegevens, Parkeren, Contact met de gemeente',
            username: 'Valentijn-van-Urquhart',
            profileId: '999990202',
          },
          {
            brpBsn: '999990202',
            mokum: true,
            hasChildren: false,
            partnerName: 'Ellen',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Belastingen, Mijn gegevens, Parkeren, Contact met de gemeente',
            username: 'valentijn12',
            profileId: '999990202',
          },
          {
            brpBsn: '999993586',
            mokum: false,
            hasChildren: false,
            partnerName: '',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: true,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas: 'Mijn gegevens, Contact met de gemeente',
            username: 'VOW1',
            profileId: '999993586',
          },
          {
            brpBsn: '999994529',
            mokum: false,
            hasChildren: false,
            partnerName: '',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: true,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas: 'Mijn gegevens, Contact met de gemeente',
            username: 'VOW2',
            profileId: '999994529',
          },
          {
            heeftStadspas: false,
            availableThemas: 'Contact met de gemeente',
            username: 'VOW3',
            profileId: '3999993963',
          },
          {
            brpBsn: '999994438',
            mokum: false,
            hasChildren: false,
            partnerName: '',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: true,
            isAdresInOnderzoek: true,
            heeftStadspas: false,
            availableThemas: 'Mijn gegevens, Contact met de gemeente',
            username: 'VOW4',
            profileId: '999994438',
          },
          {
            brpBsn: '999997233',
            mokum: false,
            hasChildren: false,
            partnerName: '',
            isOlderThan18: true,
            hasParents: false,
            hasVertrokkenOnbekendWaarheen: true,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas: 'Mijn gegevens, Contact met de gemeente',
            username: 'VOW5',
            profileId: '999997233',
          },
          {
            brpBsn: '999996915',
            mokum: true,
            hasChildren: false,
            partnerName: '',
            isOlderThan18: true,
            hasParents: false,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Afval, Mijn gegevens, Parkeren, Contact met de gemeente',
            username: 'Waclaw-Komar',
            profileId: '999996915',
          },
          {
            brpBsn: '999991267',
            mokum: true,
            hasChildren: false,
            partnerName: '',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Afval, Mijn gegevens, Parkeren, Contact met de gemeente',
            username: 'Weesper',
            profileId: '999991267',
          },
          {
            brpBsn: '999994669',
            mokum: false,
            hasChildren: true,
            partnerName: 'Jacoba Magdalena',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Belastingen, Bodem, Mijn gegevens, Horeca, Kredietbank & FIBU, Milieuzone, Contact met de gemeente, Subsidies, Toeristische verhuur, Vergunningen en ontheffingen, Zorg en ondersteuning, Inkomen',
            username: 'Wesley01',
            profileId: '129095205',
          },
          {
            brpBsn: '999990263',
            mokum: true,
            hasChildren: true,
            partnerName: 'Franciscus',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Afval, Mijn gegevens, Parkeren, Contact met de gemeente',
            username: 'Wilhelmina-Sophia-van-Deursen',
            profileId: '999990263',
          },
          {
            brpBsn: '999992181',
            mokum: true,
            hasChildren: false,
            partnerName: '',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Afval, Mijn gegevens, Parkeren, Contact met de gemeente',
            username: 'Willem-Gat',
            profileId: '999992181',
          },
          {
            brpBsn: '999993112',
            mokum: true,
            hasChildren: true,
            partnerName: 'Gerrit',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Afval, Bezwaren, Bodem, Mijn gegevens, Parkeren, Contact met de gemeente, Toeristische verhuur, Vergunningen en ontheffingen',
            username: 'Wilma-van-Zon',
            profileId: '999993112',
          },
          {
            brpBsn: '999996940',
            mokum: true,
            hasChildren: false,
            partnerName: '',
            isOlderThan18: true,
            hasParents: false,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Afval, Mijn gegevens, Parkeren, Contact met de gemeente',
            username: 'Wojciech-Partyka',
            profileId: '999996940',
          },
          {
            brpBsn: '999990809',
            mokum: true,
            hasChildren: true,
            partnerName: 'Valiallah',
            isOlderThan18: true,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Afval, Mijn gegevens, Parkeren, Contact met de gemeente',
            username: 'Zahra-Sohrabi',
            profileId: '999990809',
          },
          {
            brpBsn: '999970355',
            mokum: false,
            hasChildren: false,
            partnerName: '',
            isOlderThan18: false,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Belastingen, Bodem, Mijn gegevens, Parkeren, Contact met de gemeente, Vergunningen en ontheffingen, Zorg en ondersteuning, Inkomen',
            username: 'ZahraSohrabi02',
            profileId: '123459965',
          },
          {
            brpBsn: '999995807',
            mokum: true,
            hasChildren: false,
            partnerName: '',
            isOlderThan18: false,
            hasParents: true,
            hasVertrokkenOnbekendWaarheen: false,
            isAdresInOnderzoek: false,
            heeftStadspas: false,
            availableThemas:
              'Afval, Mijn gegevens, Parkeren, Contact met de gemeente',
            username: 'Zoey-den-Braber',
            profileId: '999995807',
          },
        ],
      },
    },
  },
  {
    id: 'get-test-accounts-eherkenning',
    url: `${MOCK_BASE_PATH}/test-accounts/eherkenning`,
    method: 'GET',
    handler: {
      type: 'json',
      status: 200,
      body: {
        tableHeaders: [
          { displayName: 'Gebruikersnaam', key: 'username' },
          { displayName: 'Profiel ID', key: 'profileId' },
        ],
        accounts: [
          {
            username: 'from-mocks-server',
            profileId: '999999999',
            fooBar: 'baz',
          },
        ],
      },
    },
  },
];
