name: CI

# Run this workflow every time a commit gets pushed to main or a pull request gets opened against main
on:
  push:
    branches:
      # - main
      - testen
      # - acceptatie
      # - production-release-*
      - ontwikkelen
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Call Azure Pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Determine Dtap
        run: |
          ref=${{ github.ref_name }}
          echo ref: $ref
          echo "DTAPNAME=${ref:0:1}" >> $GITHUB_ENV
      - name: Azure Pipelines Action
        uses: Azure/pipelines@v1.2
        with:
          azure-devops-project-url: '${{ secrets.AZURE_DEVOPS_PROJECT_URL }}'
          azure-pipeline-name: '${{ github.ref_name }}PipelineMain'
          azure-devops-token: '${{ secrets.AZURE_DEVOPS_TOKEN }}'
          azure-pipeline-variables: '{"ghTargetBranch": "${{ github.ref_name }}", "ghRepositoryName": "${{ github.event.repository.name }}", "ghDtapName": "${{ env.DTAPNAME }}"}'
